project:
  name: ccswarm
  description: AI Multi-Agent Orchestration System
  default_priority: medium
  git:
    remote: https://github.com/nwiizo/ccswarm
    default_branch: master
    worktree_dir: "../ccswarm-tickets"

ticket:
  id_prefix: "CS"
  default_tags: ["development", "feature"]
  required_fields: ["title", "description"]

workflow:
  statuses:
    - draft
    - open
    - in_progress
    - review
    - testing
    - done
    - closed
  default_status: draft

integration:
  mcp:
    enabled: true
    port: 3000
  github:
    create_pr: true
    auto_link: true