version: '3.8'
services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
  backend:
    build: ../backend
    ports:
      - "8000:8000"
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
