# vibe-ticket configuration for ccswarm project
project:
  name: ccswarm
  path: /Users/nwiizo/ghq/github.com/nwiizo/ccswarm
  default_priority: medium
  default_assignee: ""
  default_tags: []

storage:
  type: file
  path: /Users/nwiizo/ghq/github.com/nwiizo/ccswarm/.vibe-ticket/tickets

mcp:
  server:
    host: 127.0.0.1
    port: 0  # 0 means use stdio mode

ui:
  theme: dark
  editor: vi
  emoji: true
  page_size: 20